In [1]:
import numpy as np

In [5]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# can select from the array just like with a list
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
# can broadcast values across multiple positions
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# reset array
arr = np.arange(0,11)

In [9]:
# can take a segment of array
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
# can select everything in that array to make one value
slice_of_arr[:] = 50
slice_of_arr

array([50, 50, 50, 50, 50, 50])

In [11]:
# BUT this was actually a pointer to the other array so it changed that as well
# so it was a VIEW of the same array to avoid memory problems dealing with large datasets
# NOT a copy
arr

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

In [12]:
# to explicitly copy into a new array list, must use the copy command
arr_copy = arr.copy()
arr_copy

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

In [13]:
arr_copy[:] = 200
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [14]:
# original data is not modified
arr

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

In [16]:
# mat[row, column]
# - OR - 
# mat[row][column]

# create example nested array
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
# to select a certain row of a matrix
mat[1]

array([20, 25, 30])

In [20]:
# to select a certain cell such as the middle 25 number
mat[1][1]

25

In [21]:
# this is a more common notation to do the same thing
mat[1,1]

25

In [22]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
# to select a concise square within the matrix
# this select UP TO but not including row 2 and column 1 to the end
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [28]:
# starting at row 1 to the end and up to but not including column 2
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [30]:
# conditional selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# can analyze an array for boolean case matching
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [32]:
# can make a boolean array of this case
bool_arr = arr > 4

In [34]:
# applying that array to original array will supply only the True values matching the case
# NOTE the square brackets
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [35]:
# to do conditional select in a single line, use the following
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])